# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: CHILI GraFx Guides
theme:
  name: material
  custom_dir: overrides
  logo: assets/CHILI_LOGOS_OK-02.svg
  features:
    - navigation.tabs
    - content.tabs.link
  font:
    text: Ubuntu
  palette:
    primary: grey
  icon:
    admonition:
        note: material/pencil
        example: material/test-tube
        danger: material/fire-alert

plugins:
  - redirects:
      redirect_maps:
        'CHILI-GraFx/releasenotes.md': 'release-notes/index.md'
        'GraFx-Studio/releasenotes.md': 'release-notes/index.md'
  - search
  - awesome-pages
  - tags:
      tags_file: tags.md
#  - git-revision-date-localized:
#      fallback_to_build_date: true

markdown_extensions:
  - md_in_html
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      toc_depth: 3
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/feedback.js

extra:
  consent:
    title: CHILI Grafx uses cookies
    description: >-
        This website uses cookies to improve user experience. By using our website you consent to all cookies in accordance with our Cookie Policy.
        <a href="https://www.chili-publish.com/legal/" target="_blank">CHILI publish Pravacy Statement</a>
    cookies:
      analytics:
        name: Google Analytics
        checked: true
  analytics:
    provider: google
    property: G-73R676NPTP
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Let us know what you would change!
            <a href="https://forms.office.com/e/XPsgcHD0i0" target="_blank" rel="noopener">feedback form</a>


nav:
    - 'CHILI GraFx':
        - 'Introduction':                       'CHILI-GraFx/index.md'
#        - 'Setting up CHILI GraFx':             'CHILI-GraFx/setup.md'
        - 'Upgrade from My CHILI publish':      'CHILI-GraFx/guides/onboarding/upgrade/index.md'
        - 'Concepts':
            - 'Renders':                        'CHILI-GraFx/concepts/renders/index.md'
            - 'Sandbox':                        'CHILI-GraFx/concepts/sandbox/index.md'
        - 'Platform Admin':
            - 'General Admin' :                 'CHILI-GraFx/admin/index.md'
            - 'User management' :
                - 'Intro' :                     'CHILI-GraFx/users/intro/index.md'
                - 'Scope' :                     'CHILI-GraFx/users/scope/index.md'
                - 'Roles' :                     'CHILI-GraFx/users/roles/index.md'
                - 'Change Roles & Access' :     'CHILI-GraFx/users/update/index.md'
                - 'Template Designer Seat' :    'CHILI-GraFx/users/template-designer/index.md'
                - 'Users & Invitation' :        'CHILI-GraFx/users/creation/index.md'
#                - 'Scenarios' :                 'CHILI-GraFx/users/scenarios/index.md'
#            - 'Subscriptions' :                 'CHILI-GraFx/subscriptions/index.md'
#            - 'Environments' :                  'CHILI-GraFx/environments/index.md'
#        - 'Application overview':
#            - 'Panel 1' :                       'CHILI-GraFx/panel1.md'
        - 'How to':
#            - 'Create a new environment' :      'CHILI-GraFx/guides/create-environment/index.md'
            - 'Create GraFx Studio template' :   'CHILI-GraFx/guides/create-studio-template/index.md'
            - 'Create GraFx Publisher template' : 'CHILI-GraFx/guides/create-publisher-template/index.md'
        - 'Integrate CHILI GraFx':
            - 'Getting started' :               'CHILI-GraFx/integration/getting_started.md'
        - 'Step by step onboarding':
            - 'Intro' :                         'CHILI-GraFx/guides/onboarding/intro/index.md'
            - 'User Account Migration' :        'CHILI-GraFx/guides/onboarding/migration/index.md'
            - 'Logging in' :                     'CHILI-GraFx/guides/onboarding/logging-in/index.md'
            - 'Find your way around' :          'CHILI-GraFx/guides/onboarding/navigation/index.md'
            - 'Applications' :                  'CHILI-GraFx/guides/onboarding/applications/index.md'
            #TODO(austin): Discuss if these items should be moved to GraFx-Stduio and GraFx-Publisher
            - 'GraFx Publisher' :
                - 'GraFx Publisher - first template': 'CHILI-GraFx/step_by_step/gfx_publisher_template1.md'
            - 'GraFx Studio' :
                - 'Hello world':                'CHILI-GraFx/step_by_step/gfx_studio_template1.md'
                - 'Hello world extended':       'CHILI-GraFx/step_by_step/gfx_studio_template2.md'
#                - 'Adding a text frame':        'CHILI-GraFx/step_by_step/gfx_studio_textframe.md'
#                - 'Adding an image frame':      'CHILI-GraFx/step_by_step/gfx_studio_imageframe.md'
#                - 'Styles':                     'CHILI-GraFx/step_by_step/gfx_studio_styles.md'
#                - 'Layouts':                    'CHILI-GraFx/step_by_step/gfx_studio_layouts.md'
#                - 'Timeline':                   'CHILI-GraFx/step_by_step/gfx_studio_timeline.md'
            - 'GraFx Media' :
                - 'GraFx Media intro':              'CHILI-GraFx/step_by_step/gfx_media.md'
        - 'Release notes':                      'release-notes/index.md'

    - 'GraFx Studio':
        - 'Introduction':                       'GraFx-Studio/index.md'
        - 'Application overview':
            - 'Workspace elements':             'GraFx-Studio/overview/workspace-elements/index.md'
            - 'Mouse or Trackpad':              'GraFx-Studio/overview/movement/index.md'
            - 'Header Bar':                     'GraFx-Studio/overview/headerbar/index.md'
            - 'Sidebar Tools':                  'GraFx-Studio/overview/sidebar/index.md'
            - 'Document Canvas':                'GraFx-Studio/overview/document-canvas/index.md'
            - 'Page or Document':               'GraFx-Studio/overview/page-document/index.md'
            - 'Properties panel':               'GraFx-Studio/overview/properties/index.md'
            - 'Export':                         'GraFx-Studio/overview/export/index.md'
            - 'Bottom Quick Tools':             'GraFx-Studio/overview/bottom-quicktools/index.md'
            - 'Animation':                      'GraFx-Studio/overview/animation/index.md'
            - 'Layouts':                        'GraFx-Studio/overview/layouts/index.md'
            - 'Frames & Timeline':              'GraFx-Studio/overview/frames-timeline/index.md'
            - 'Stylekit':                       'GraFx-Studio/overview/stylekits/index.md'
        - 'Concepts':
#            - 'Template vs Publication':        'GraFx-Studio/concept/template_publication.md'
            - 'Frames':                         'GraFx-Studio/concepts/frames/index.md'
            - 'Layers':                         'GraFx-Studio/concepts/layers/index.md'
            - 'Layouts':                        'GraFx-Studio/concepts/layouts/index.md'
            - 'Shapes':                         'GraFx-Studio/concepts/shapes/index.md'
            - 'Variables':                      'GraFx-Studio/concepts/variables/index.md'
            - 'Blend modes':                    'GraFx-Studio/concepts/blendmodes/index.md'
            - 'Animation':                      'GraFx-Studio/concepts/animation/index.md'
            - 'Stylekits':                      'GraFx-Studio/concepts/stylekits/index.md'
            - 'Keyboard Shortcuts':             'GraFx-Studio/concepts/shortcuts/index.md'
        - 'How to: Design documents':
            - 'Create Layouts':                 'GraFx-Studio/guides/layouts/index.md'
            - 'Paragraph Styles':               'GraFx-Studio/guides/paragraphstyles/index.md'
            - 'Character Styles':               'GraFx-Studio/guides/characterstyles/index.md'
            - 'Swatches':                       'GraFx-Studio/guides/swatches/index.md'
            - 'Blend modes':                    'GraFx-Studio/guides/blendmodes/index.md'
            - 'Animate my frame':               'GraFx-Studio/guides/animate-frame/index.md'
            - 'Define variables':               'GraFx-Studio/guides/variables/define/index.md'
            - 'Organize variables':             'GraFx-Studio/guides/variables/organize/index.md'
            - 'Add variables to document':      'GraFx-Studio/guides/variables/index.md'
#        - 'How to: Extend GraFx studio':
#            - 'GraFx studio INDD plugin' :      'GraFx-Studio/plugin/studio_indesign.md'
#            - 'GraFx studio AI plugin' :        'GraFx-Studio/plugin/studio_ai.md'
        - 'How to: Output':
#            - 'Settings':                       'GraFx-Studio/guides/output/settings/index.md'
            - 'MP4':                            'GraFx-Studio/guides/output/mp4/index.md'
            - 'GIF':                            'GraFx-Studio/guides/output/gif/index.md'
            - 'JPG and PNG':                    'GraFx-Studio/guides/output/image/index.md'
        - 'Integrate GraFx studio':
            - 'Getting started':                'GraFx-Studio/integration/getting_started.md'
            - 'Local environment':              'GraFx-Studio/integration/local_environment.md'
            - 'NPM & Webpack':                  'GraFx-Studio/integration/npm_webpack.md'
            - 'CHILI Editor SDK':               'GraFx-Studio/integration/chili_editor_sdk.md'
            - 'First build':                    'GraFx-Studio/integration/first_build.md'
            - 'Custom app':                     'GraFx-Studio/integration/custom_app.md'
        - 'Release notes':                      'release-notes/index.md'
    - 'GraFx Publisher':
        - 'Introduction':                       'GraFx-Publisher/index.md'

    - 'GraFx Media':
        - 'Introduction':                       'GraFx-Media/index.md'
        - 'Application overview':
            - 'Viewing Media':                    'GraFx-Media/overview/viewing/index.md'
        - 'How to':
            - 'Browse media':                     'GraFx-Media/guides/browse/index.md'
            - 'Search media':                     'GraFx-Media/guides/search/index.md'
#           'Upload media':                     'GraFx-Media/guides/upload/index.md'
#           'Download media':                   'GraFx-Media/guides/download/index.md'
#           'Sort and Filter media':            'GraFx-Media/guides/filter/index.md'
#           'Sort media':                       'GraFx-Media/guides/sort/index.md'

    - 'GraFx Fonts':
        - 'Introduction':                       'GraFx-Fonts/index.md'
#        - 'Environment API':                    '/CHILI-GraFx/api/environment/index.md'

    - 'GraFx Stylekits':
        - 'Introduction':                       'GraFx-Stylekits/index.md'
#        - 'Environment API':                    '/CHILI-GraFx/api/environment/index.md'

#    - 'Solutions':
#        - 'Multiple adds in Real Estate':       'solutions/realestate.md'

    - 'Release notes':
        - 'Recent':                             'release-notes/index.md'
        - '2022':                               'release-notes/2022.md'


    - 'Developer center':
        - 'Overview':                           'GraFx-Developers/index.md'
        - 'GraFx Studio SDK':                   'https://chili-publish.github.io/editor-sdk/index.html'
        - 'Platform API reference' :
            - 'Swagger' :                       'https://api.chiligrafx.com/swagger/index.html'
        - 'Environment API reference':
            - 'Swagger' :                       'https://sandbox1.chili-publish-sandbox.online/grafx/swagger/index.html'